### PR TITLE
Changes after feedback and experiences from Mechelen

### PR DESCRIPTION
**Pull request by IObert**
As discussed

### CODE REVIEW

**Comment by rpanneel** [comment]
Hi Marius,

I was thinking about our conversation in Mechelen about the Windows issues. 

Besides the fix and the option to use a Docker container you could also use the [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10). Then the bash of Linux and the Linux kernel could be used to run all the commands.

That way you could also avoid the issues with windows I guess.

But the same issue as for Docker: this would mean a heavier prerequisites step and the risk that people are getting confused with another layer of complexity.

Regards,

Robin

**Comment by IObert** [comment]
Hi Robin,

thanks for your feedback. I agree that we should keep the setup as simple as possible and reduce the number of involved tools to a minimum. When I got back to Munich, I provisioned a Windows VM on Azure and tested the content with the updated steps successfully. That's why I think the main problem was that many attendees didn't install all the required tools at the beginning (or they had older versions installed). In retrospective, I think, that the confusion about installing new tools at the last exercise might have been the reason why we couldn't focus on the "real windows issues" the attendees had. In the very next Codejam, we will try to make sure that all required are installed before we start with exercise 10.

Enabling the Linux subsystem is also a very interesting approach we could apply for the Codejams were we have a little bit more time to adjust the content. Did you already try this on your machine? If so, did you have the feeling that it was easier this way?

Regards,
Marius

**Comment by rpanneel** [comment]
Hi Marius,

I have not yet tried it. I'm hoping to play around with it this week-end, so I will provide you with some feedback once my test is done.

Regards,

Robin

**Comment by qmacro** [comment]
Thanks for the thoughts, Robin! WSL is indeed an interesting option, but unfortunately it wouldn't solve all the issues for all the Windows users as it's not available across the board. 

In my thoughts on this so far, I am tending towards favouring a Docker based approach. After all, containers are the solution to so many other things, for good reason (abstraction and compartmentalisation), and makes a lot of sense to use it here too, to achieve a reliable, predictable and uniform build environment. And the availability of Docker for different OSes today (even Windows) is more than good enough to be able to give us a single install requirement for build. 

That's the theory anyway! :-)

**Review by qmacro — APPROVED** [review]
I've made some changes directly to your changes. Thanks.

**Pull request merged**
